services:
  db:
    image: postgres:16
    container_name: habitflow-db
    environment:
      POSTGRES_USER: habitflow
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: habitflow_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habitflow -d habitflow_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: habitflow-backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://habitflow:devpassword@db:5432/habitflow_dev
      JWT_SECRET: dev-secret-change-in-production
      PORT: 3001
      CORS_ORIGIN: http://localhost:3000
      STRIPE_SECRET_KEY: sk_test_placeholder
      STRIPE_PUBLISHABLE_KEY: pk_test_placeholder
      STRIPE_WEBHOOK_SECRET: whsec_placeholder
      VAPID_PUBLIC_KEY: BC3j9sjjuAySp1vVoU6CQU4GGbu7t2jg_zxS8S8PYcEYFx1BO2X-FlssF7Y62iNMWgXYqll9fFfO4n99p7r4k60
      VAPID_PRIVATE_KEY: ibcn5RNzmB9n-Tr239FZIrIFyV_eYckKuslL8h9EHds
      VAPID_MAILTO: mailto:jep@example.com
    depends_on:
      db:
        condition: service_healthy
#    volumes:
#      - ./backend:/app
#      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: habitflow-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - backend

volumes:
  pgdata: